# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApiCheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AllWindows(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(750, 410)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 751, 411))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.gridLayoutWidget = QtWidgets.QWidget(self.mainPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 80, 591, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.whichCity = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.whichCity.setObjectName("whichCity")
        self.gridLayout.addWidget(self.whichCity, 0, 1, 1, 1)
        self.targetButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.targetButton.setObjectName("targetButton")
        self.gridLayout.addWidget(self.targetButton, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.mainPage)
        self.label.setGeometry(QtCore.QRect(291, 20, 160, 60))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typo")
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.mainPage)
        self.label_3.setGeometry(QtCore.QRect(20, 260, 710, 25))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.mainPage)
        self.label_4.setGeometry(QtCore.QRect(20, 275, 710, 25))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.mainPage)
        self.label_5.setGeometry(QtCore.QRect(20, 290, 710, 25))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.mainPage)
        self.label_6.setGeometry(QtCore.QRect(20, 315, 710, 25))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.mainPage)
        self.label_7.setGeometry(QtCore.QRect(20, 330, 710, 25))
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.mainPage)
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        self.mutualInputButton = QtWidgets.QPushButton(self.page1)
        self.mutualInputButton.setGeometry(QtCore.QRect(630, 90, 90, 25))
        self.mutualInputButton.setObjectName("mutualInputButton")
        self.mutualListWidget = QtWidgets.QListWidget(self.page1)
        self.mutualListWidget.setGeometry(QtCore.QRect(20, 160, 701, 221))
        self.mutualListWidget.setObjectName("mutualListWidget")
        self.mutualMainLabel = QtWidgets.QLabel(self.page1)
        self.mutualMainLabel.setGeometry(QtCore.QRect(240, 20, 251, 31))
        self.mutualMainLabel.setObjectName("mutualMainLabel")
        self.mutualLineEdit = QtWidgets.QLineEdit(self.page1)
        self.mutualLineEdit.setGeometry(QtCore.QRect(20, 90, 601, 25))
        self.mutualLineEdit.setObjectName("mutualLineEdit")
        self.backMenuButton1 = QtWidgets.QPushButton(self.page1)
        self.backMenuButton1.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.backMenuButton1.setObjectName("backMenuButton1")
        self.mutualInputLabel = QtWidgets.QLabel(self.page1)
        self.mutualInputLabel.setGeometry(QtCore.QRect(20, 60, 701, 20))
        self.mutualInputLabel.setObjectName("mutualInputLabel")
        self.mutualNameLabel = QtWidgets.QLabel(self.page1)
        self.mutualNameLabel.setGeometry(QtCore.QRect(20, 130, 701, 17))
        self.mutualNameLabel.setText("")
        self.mutualNameLabel.setObjectName("mutualNameLabel")
        self.stackedWidget.addWidget(self.page1)
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        self.targetNextButton = QtWidgets.QPushButton(self.page2)
        self.targetNextButton.setGeometry(QtCore.QRect(630, 340, 89, 25))
        self.targetNextButton.setObjectName("targetNextButton")
        self.targetLineEdit = QtWidgets.QLineEdit(self.page2)
        self.targetLineEdit.setGeometry(QtCore.QRect(20, 90, 601, 25))
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.targetInputLabel = QtWidgets.QLabel(self.page2)
        self.targetInputLabel.setGeometry(QtCore.QRect(20, 60, 701, 17))
        self.targetInputLabel.setObjectName("targetInputLabel")
        self.backMenuButton2 = QtWidgets.QPushButton(self.page2)
        self.backMenuButton2.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.backMenuButton2.setObjectName("backMenuButton2")
        self.targetListWidget = QtWidgets.QListWidget(self.page2)
        self.targetListWidget.setGeometry(QtCore.QRect(20, 130, 701, 192))
        self.targetListWidget.setObjectName("targetListWidget")
        self.targetMainLabel = QtWidgets.QLabel(self.page2)
        self.targetMainLabel.setGeometry(QtCore.QRect(300, 20, 131, 31))
        self.targetMainLabel.setObjectName("targetMainLabel")
        self.targetInputButton = QtWidgets.QPushButton(self.page2)
        self.targetInputButton.setGeometry(QtCore.QRect(630, 90, 90, 25))
        self.targetInputButton.setObjectName("targetInputButton")
        self.checkBox = QtWidgets.QCheckBox(self.page2)
        self.checkBox.setGeometry(QtCore.QRect(20, 375, 421, 25))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.page2)
        self.pushButton.setGeometry(QtCore.QRect(460, 375, 261, 25))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page2)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trace"))
        self.whichCity.setText(_translate("MainWindow", "Узнать город"))
        self.targetButton.setText(_translate("MainWindow",
                                             "Целевая аудитория"))
        self.label.setText(_translate("MainWindow", "Trace"))
        self.label_3.setText(_translate("MainWindow",
                                        "Trace - Программа по работе с данными Вконтакте,"
                                        "Trace поможет вам определить людей, которые"))
        self.label_4.setText(_translate("MainWindow",
                                        "подписаны на 2 и более сообществ (кнопка "
                                        "\"Целевая аудитория\"), для выявления целевой "
                                        "ауди-"))
        self.label_5.setText(
            _translate("MainWindow", "аудитории на показ рекламы, имеет "
                                     "функцию вывода их уникальных номеров в "
                                     "файл."))
        self.label_6.setText(_translate("MainWindow",
                                        "Кнопка \"Узнать город\", поможет "
                                        "определить в каком городе живет "
                                        "человек, благодаря парсингу"))
        self.label_7.setText(_translate("MainWindow", "городов его друзей."))
        self.mutualInputButton.setText(_translate("MainWindow", "Далее"))
        self.mutualMainLabel.setText(_translate("MainWindow",
                                                "Предположительное местоположение"))
        self.backMenuButton1.setText(_translate("MainWindow", "< В меню"))
        self.mutualInputLabel.setText(
            _translate("MainWindow", "Введите ссылку на человека, "
                                     "местоположение которого нужно найти"))
        self.targetNextButton.setText(_translate("MainWindow", "Далее"))
        self.targetInputLabel.setText(
            _translate("MainWindow", "Введите название или ссылку на группы у"
                                     " которых нужно найти общих подписчиков"))
        self.backMenuButton2.setText(_translate("MainWindow", "< В меню"))
        self.targetMainLabel.setText(_translate("MainWindow",
                                                "Целевая аудитория"))
        self.targetInputButton.setText(_translate("MainWindow", "Ввести"))
        self.checkBox.setText(_translate("MainWindow", "Вывести имена, id и "
                                                       "город (занимает много "
                                                       "времени)"))
        self.pushButton.setText(_translate("MainWindow", "Вывести в файл"))