# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApiCheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("QMainWidget")
        self.resize(410, 120)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(20, 10, 371, 17))
        self.MainLabel.setObjectName("MainLabel")
        self.MainLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.MainLineEdit.setGeometry(QtCore.QRect(60, 40, 291, 25))
        self.MainLineEdit.setObjectName("MainLineEdit")
        self.MainButton = QtWidgets.QPushButton(self.centralwidget)
        self.MainButton.setGeometry(QtCore.QRect(160, 80, 100, 25))
        self.MainButton.setObjectName("MainButton")
        self.gifLabel = QtWidgets.QLabel(self.centralwidget)
        self.gifLabel.setGeometry(QtCore.QRect(353, 40, 25, 25))
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, QMainWidget):
        _translate = QtCore.QCoreApplication.translate
        QMainWidget.setWindowTitle(_translate("QMainWidget", "Проверка API"))
        self.MainLabel.setText(_translate("QMainWidget", "Для дальнейшей "
                                                         "работы нужно ваше API вконтакте"))
        self.MainButton.setText(_translate("QMainWidget", "ок"))